# Ref: https://wanago.io/2023/01/16/api-nestjs-docker-compose/

version: '3.8'

services:
  redis:
    image: "redis:6.0-alpine"
    ports:
      - "6379:6379"
  
  # enable only when target image exists
  service:
    image: nest_subscriber:v1
    restart: always
    deploy:
      replicas: 2
    depends_on:
      - redis
    environment:
      - QUEUE_HOST=redis

